export const COPING_ALPHABET = [
    { letter: 'A', action: 'Ask for help', icon: 'help-circle' },
    { letter: 'B', action: 'Breathe deeply and slowly', icon: 'wind' },
    { letter: 'C', action: 'Count forwards or backwards', icon: 'hash' },
    { letter: 'D', action: 'Drink some cold water', icon: 'droplet' },
    { letter: 'E', action: 'Exercise - Run, jump, skip', icon: 'activity' },
    { letter: 'F', action: 'Find a safe place', icon: 'home' },
    { letter: 'G', action: 'Go to your happy place', icon: 'map-pin' },
    { letter: 'H', action: 'Hug a friend or family member', icon: 'heart' },
    { letter: 'I', action: 'Ignore people who are annoying you', icon: 'user-x' },
    { letter: 'J', action: 'Jokes to help you laugh', icon: 'laugh' },
    { letter: 'K', action: 'Kind hands, keep them to yourself', icon: 'hand' },
    { letter: 'L', action: 'Listen to calming music', icon: 'music' },
    { letter: 'M', action: 'Meditate - Use yoga or mindfulness', icon: 'brain' },
    { letter: 'N', name: 'Name the emotion', action: 'Name the emotion you are feeling', icon: 'tag' },
    { letter: 'O', action: 'Observe - use mindfulness techniques', icon: 'eye' },
    { letter: 'P', action: 'Paint Your feelings', icon: 'palette' },
    { letter: 'Q', action: 'Question Your thoughts', icon: 'help-circle' },
    { letter: 'R', action: 'Run As fast as you can', icon: 'fast-forward' },
    { letter: 'S', action: 'Separate yourself from the situation', icon: 'scissors' },
    { letter: 'T', action: 'Thoughts negative to positive', icon: 'refresh-cw' },
    { letter: 'U', action: 'Use your safe place', icon: 'shield' },
    { letter: 'V', action: 'Voice your concerns', icon: 'mic' },
    { letter: 'W', action: 'Write Down your feelings', icon: 'pen-tool' },
    { letter: 'X', action: 'Exhale - Breathe out your feelings', icon: 'wind' },
    { letter: 'Y', action: 'Yell As loud as you can into a pillow', icon: 'volume-2' },
    { letter: 'Z', action: 'Zone out and relax yourself', icon: 'cloud' }
];
