export const MOOD_BATTERY_ACTIONS = [
    { id: 'mb-1', action: 'Call up a friend', trigger: "I'm feeling alone.", icon: 'phone', category: 'social', why: "Talking to a friend makes us feel loved and connected!" },
    { id: 'mb-2', action: 'Tell someone "I LOVE YOU"', trigger: "I don't feel loved.", icon: 'heart', category: 'social', why: "Sharing love makes both you and the other person feel happy!" },
    { id: 'mb-3', action: 'Write about how you feel', trigger: "I have big feelings inside.", icon: 'pen-tool', category: 'reflection', why: "Putting feelings into words helps them feel smaller and easier to handle." },
    { id: 'mb-4', action: 'Celebrate what\'s working', trigger: "Everything is going wrong.", icon: 'party-popper', category: 'reflection', why: "Remembering good things helps us find our smile again!" },
    { id: 'mb-5', action: 'Eat something healthy', trigger: "I feel weak and hungry.", icon: 'apple', category: 'physical', why: "Good food gives your body the energy it needs to bounce back!" },
    { id: 'mb-6', action: 'Find a dog', trigger: "I need a furry friend.", icon: 'dog', category: 'social', why: "Animals are great listeners and their wagging tails are full of joy!" },
    { id: 'mb-7', action: 'Take a time out', trigger: "Everything is too much!", icon: 'timer', category: 'rest', why: "A little break gives your brain a chance to rest and reset." },
    { id: 'mb-8', action: 'Go outside', trigger: "I've been inside too long.", icon: 'sun', category: 'physical', why: "Fresh air and sunshine are like a big hug for your mood!" },
    { id: 'mb-9', action: 'Look at pretty art', trigger: "The world looks gray today.", icon: 'palette', category: 'reflection', why: "Beautiful colors can inspire us and change how we see the world." },
    { id: 'mb-10', action: 'Trash negative thoughts', trigger: "I'm not good at anything.", icon: 'trash-2', category: 'mind', why: "Throwing away mean thoughts makes room for kind ones!" },
    { id: 'mb-11', action: 'Drink warm tea', trigger: "My body feels cold and tense.", icon: 'cup-soda', category: 'physical', why: "Something warm inside helps your whole body feel soft and relaxed." },
    { id: 'mb-12', action: 'Remember how far you have come', trigger: "I'll never get this right.", icon: 'trending-up', category: 'mind', why: "You've learned so many things already! You can do this too." },
    { id: 'mb-13', action: 'Wear something comfy', trigger: "My clothes are too tight.", icon: 'shirt', category: 'physical', why: "Being cozy helps your body feel safe and calm." },
    { id: 'mb-14', action: 'Remember you\'re small', trigger: "Problems feel like giants.", icon: 'globe', category: 'mind', why: "The world is so big, and these little problems will eventually drift away." },
    { id: 'mb-15', action: 'Compliment yourself', trigger: "I'm being too hard on myself.", icon: 'smile', category: 'mind', why: "You are amazing! Saying kind things to yourself is very important." },
    { id: 'mb-16', action: 'Don\'t overbook', trigger: "I have too much to do today.", icon: 'calendar-off', category: 'rest', why: "Having 'doing nothing' time is a great way to recharge." },
    { id: 'mb-17', action: 'Consider how you\'re lucky', trigger: "Why does this happen to me?", icon: 'clover', category: 'mind', why: "Focusing on our 'lucky' things helps us feel rich in our hearts." },
    { id: 'mb-18', action: 'Listen to happy tunes', trigger: "It's too quiet and sad.", icon: 'music', category: 'rest', why: "Music can dance right into your heart and make you want to wiggle!" },
    { id: 'mb-19', action: 'Slow down', trigger: "I'm rushing too fast!", icon: 'wind', category: 'rest', why: "Moving slowly helps you notice the beautiful things around you." },
    { id: 'mb-20', action: 'Be your own cheerleader', trigger: "I feel like giving up.", icon: 'megaphone', category: 'social', why: "You can cheer yourself on! You're your own best friend." }
];
